{% set name = "segment-geospatial" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segment-geospatial-{{ version }}.tar.gz
  sha256: 621e66d90715a288909c8bec6eda44e475c6f5ceceac5c8e999ff3ca49bbd194

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - segment-anything
    - opencv
    - pycocotools
    - matplotlib-base
    - onnxruntime 
    - onnx
    - geopandas
    - rasterio
    - tqdm

test:
  imports:
    - samgeo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opengeos/segment-geospatial
  summary: Meta AI' Segment Anything Model (SAM) for Geospatial Data
  description: Meta AI' Segment Anything Model (SAM) for Geospatial Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
