{% set name = "segment-geospatial" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segment-geospatial-{{ version }}.tar.gz
  sha256: ccd02f71751dcbb23c48df3ce64e607dcdafe58a058a458a2bc1996fc5127d17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - segment-anything
    - opencv
    - pycocotools
    - matplotlib-base
    - onnxruntime 
    - onnx
    - geopandas
    - rasterio
    - tqdm

test:
  imports:
    - samgeo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opengeos/segment-geospatial
  summary: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  description: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  doc_url: https://geosam.gishub.org
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
